services:
  app:
    image: ${IMAGE_NAME}
    ports:
      - "80:80"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    restart: always
