user root;
worker_processes auto;
pcre_jit on;
error_log /dev/stdout info;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /dev/stdout;
    server_tokens off;
    client_max_body_size 10m;
    sendfile on;
    tcp_nodelay on;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

    # Include all server configs
    include /etc/nginx/http.d/*.conf;
}

daemon off;